In [1]:
# File: Homework 8

In [2]:
import pandas as pd

In [3]:
state_data = pd.read_csv("../../course_assignments/homework8/state_data.csv")

In [7]:
print("Shape:", state_data.shape)
print("Number of rows:", state_data.shape[0])
print("Number of columns:", state_data.shape[1])

Shape: (52, 4)
Number of rows: 52
Number of columns: 4

In [9]:
display(state_data.head())
display(state_data.tail())
print("\nFirst state:", state_data.iloc[0]['state'])
print("Last state:", state_data.iloc[-1]['state'])
print("Total entries:", len(state_data))
print("There are more than 50 because it includes territories.")

  state   latitude   longitude        name
0    AK  63.588753 -154.493062      Alaska
1    AL  32.318231  -86.902298     Alabama
2    AR  35.201050  -91.831833    Arkansas
3    AZ  34.048928 -111.093731     Arizona
4    CA  36.778261 -119.417932  California

   state   latitude   longitude           name
47    VT  44.558803  -72.577841        Vermont
48    WA  47.751074 -120.740139     Washington
49    WI  43.784440  -88.787868      Wisconsin
50    WV  38.597626  -80.454903  West Virginia
51    WY  43.075968 -107.290284        Wyoming

First state: AK
Last state: WY
Total entries: 52
There are more than 50 because it includes territories.

In [10]:
median_lat = state_data['latitude'].median()
median_lon = state_data['longitude'].median()
print(f"Median Latitude: {median_lat:.2f}, Median Longitude: {median_lon:.2f}")

Median Latitude: 39.44, Median Longitude: -89.09

In [12]:
state_data['lat_diff'] = abs(state_data['latitude'] - median_lat)

In [13]:
state_data['lon_diff'] = abs(state_data['longitude'] - median_lon)

In [14]:
print("New shape:", state_data.shape)

New shape: (52, 6)

In [15]:
closest_lat = state_data.loc[state_data['lat_diff'].idxmin()]
farthest_lat = state_data.loc[state_data['lat_diff'].idxmax()]
closest_lon = state_data.loc[state_data['lon_diff'].idxmin()]
farthest_lon = state_data.loc[state_data['lon_diff'].idxmax()]

print(f"Closest to median latitude: {closest_lat['state']} ({closest_lat['lat_diff']:.2f})")
print(f"Farthest from median latitude: {farthest_lat['state']} ({farthest_lat['lat_diff']:.2f})")
print(f"Closest to median longitude: {closest_lon['state']} ({closest_lon['lon_diff']:.2f})")
print(f"Farthest from median longitude: {farthest_lon['state']} ({farthest_lon['lon_diff']:.2f})")

Closest to median latitude: CO (0.11)
Farthest from median latitude: AK (24.15)
Closest to median longitude: IL (0.31)
Farthest from median longitude: HI (66.57)

In [20]:
state_data_copy = state_data.copy()

print("Original DataFrame:")
display(state_data.head())
print("Copied DataFrame:")
display(state_data_copy.head())

# I found the .copy() function on the website under the "Essential Basic Functionality" tab.
# It duplicates both the data and the structure so changes made won't affect the original data frame.
# This is useful because it could prevent unintentional changes to the original data.

Original DataFrame:

  state   latitude   longitude        name   lat_diff   lon_diff
0    AK  63.588753 -154.493062      Alaska  24.153237  65.399864
1    AL  32.318231  -86.902298     Alabama   7.117285   2.190900
2    AR  35.201050  -91.831833    Arkansas   4.234465   2.738635
3    AZ  34.048928 -111.093731     Arizona   5.386588  22.000533
4    CA  36.778261 -119.417932  California   2.657255  30.324734

Copied DataFrame:

  state   latitude   longitude        name   lat_diff   lon_diff
0    AK  63.588753 -154.493062      Alaska  24.153237  65.399864
1    AL  32.318231  -86.902298     Alabama   7.117285   2.190900
2    AR  35.201050  -91.831833    Arkansas   4.234465   2.738635
3    AZ  34.048928 -111.093731     Arizona   5.386588  22.000533
4    CA  36.778261 -119.417932  California   2.657255  30.324734